version: '1'
services:
  generic_translator_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: generic_translator_service
      INGRESS_HOST: 127.0.0.1
      INGRESS_PORT: 80
